name: GPax
channels:
  - conda-forge
  - defaults
dependencies:
  - jax
  - pip
  - pandas
  - python=3.8
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - pip:
    - dm-tree
    - flax==0.7
    - tensorflow
    - tensorflow-probability==0.21
